/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bfkgnnnxyooretgrxedo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJma2dubm54eW9vcmV0Z3J4ZWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNjU5MzgsImV4cCI6MjA4Mjk0MTkzOH0.yjHtV8Rr1lQD6u-AA5XadWGOgMzw9Ai-9cEWuHNqFng"